version: '3'

services:
  match-list-change-detector:
    build: .
    container_name: match-list-change-detector
    environment:
      - FOGIS_USERNAME=${FOGIS_USERNAME}
      - FOGIS_PASSWORD=${FOGIS_PASSWORD}
      - DAYS_BACK=${DAYS_BACK:-7}
      - DAYS_AHEAD=${DAYS_AHEAD:-365}
      - DOCKER_COMPOSE_FILE=${ORCHESTRATOR_DOCKER_COMPOSE_PATH:-../MatchListProcessor/docker-compose.yml}
      - TZ=Europe/Stockholm
    volumes:
      - ./previous_matches.json:/app/previous_matches.json
      - ./match_changes.json:/app/match_changes.json
      - ./match_list_change_detector.log:/app/match_list_change_detector.log
      - ${ORCHESTRATOR_DOCKER_COMPOSE_PATH:-../MatchListProcessor/docker-compose.yml}:/app/orchestrator-docker-compose.yml
    networks:
      - ${CONTAINER_NETWORK:-fogis-network}
    restart: unless-stopped

networks:
  fogis-network:
    external: true
