version: '3.8'

services:
  # Persistent service mode - runs continuously with HTTP server and internal scheduling
  match-list-change-detector-persistent:
    build: .
    container_name: match-list-change-detector-persistent
    environment:
      # Service mode configuration
      - RUN_MODE=service                    # Enable persistent service mode
      - CRON_SCHEDULE=${CRON_SCHEDULE:-0 * * * *}  # Hourly execution (configurable)
      - HEALTH_SERVER_PORT=8000
      - HEALTH_SERVER_HOST=0.0.0.0

      # API credentials
      - FOGIS_USERNAME=${FOGIS_USERNAME}
      - FOGIS_PASSWORD=${FOGIS_PASSWORD}

      # Match list configuration
      - DAYS_BACK=${DAYS_BACK:-7}
      - DAYS_AHEAD=${DAYS_AHEAD:-365}
      - PREVIOUS_MATCHES_FILE=${PREVIOUS_MATCHES_FILE:-previous_matches.json}

      # Orchestrator configuration
      - DOCKER_COMPOSE_FILE=${DOCKER_COMPOSE_FILE:-../MatchListProcessor/docker-compose.yml}

      # Logging configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_DIR=/app/logs
      - LOG_FILE=${LOG_FILE:-match_list_change_detector.log}

      # Timezone
      - TZ=${TZ:-Europe/Stockholm}
    ports:
      - "8000:8000"  # HTTP server for health checks and manual triggers
    volumes:
      # Data files
      - ./data:/app/data

      # Logs
      - ./logs:/app/logs

      # Orchestrator docker-compose file
      - ${DOCKER_COMPOSE_FILE:-../MatchListProcessor/docker-compose.yml}:/app/orchestrator-docker-compose.yml
    networks:
      - ${CONTAINER_NETWORK:-fogis-network}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Traditional oneshot mode - runs once and exits (original behavior)
  match-list-change-detector-oneshot:
    build: .
    container_name: match-list-change-detector-oneshot
    environment:
      # Service mode configuration
      - RUN_MODE=oneshot                    # Traditional oneshot mode

      # API credentials
      - FOGIS_USERNAME=${FOGIS_USERNAME}
      - FOGIS_PASSWORD=${FOGIS_PASSWORD}

      # Match list configuration
      - DAYS_BACK=${DAYS_BACK:-7}
      - DAYS_AHEAD=${DAYS_AHEAD:-365}
      - PREVIOUS_MATCHES_FILE=${PREVIOUS_MATCHES_FILE:-previous_matches.json}

      # Orchestrator configuration
      - DOCKER_COMPOSE_FILE=${DOCKER_COMPOSE_FILE:-../MatchListProcessor/docker-compose.yml}

      # Logging configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_DIR=/app/logs
      - LOG_FILE=${LOG_FILE:-match_list_change_detector.log}

      # Timezone
      - TZ=${TZ:-Europe/Stockholm}
    volumes:
      # Data files
      - ./data:/app/data

      # Logs
      - ./logs:/app/logs

      # Orchestrator docker-compose file
      - ${DOCKER_COMPOSE_FILE:-../MatchListProcessor/docker-compose.yml}:/app/orchestrator-docker-compose.yml
    networks:
      - ${CONTAINER_NETWORK:-fogis-network}
    # Note: No restart policy for oneshot mode - container exits after execution

networks:
  fogis-network:
    external: true

volumes:
  data:
    driver: local
