version: '3'

services:
  match-list-change-detector:
    build: .
    container_name: match-list-change-detector
    environment:
      # API credentials
      - FOGIS_USERNAME=${FOGIS_USERNAME}
      - FOGIS_PASSWORD=${FOGIS_PASSWORD}

      # Match list configuration
      - DAYS_BACK=${DAYS_BACK:-7}
      - DAYS_AHEAD=${DAYS_AHEAD:-365}
      - PREVIOUS_MATCHES_FILE=${PREVIOUS_MATCHES_FILE:-previous_matches.json}

      # Orchestrator configuration
      - DOCKER_COMPOSE_FILE=${DOCKER_COMPOSE_FILE:-../MatchListProcessor/docker-compose.yml}

      # Logging configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_DIR=/app/logs
      - LOG_FILE=${LOG_FILE:-match_list_change_detector.log}

      # Timezone
      - TZ=${TZ:-Europe/Stockholm}
    ports:
      - "8000:8000"  # Metrics and health check
    volumes:
      # Data files
      - ./data:/app/data

      # Logs
      - ./logs:/app/logs

      # Orchestrator docker-compose file
      - ${DOCKER_COMPOSE_FILE:-../MatchListProcessor/docker-compose.yml}:/app/orchestrator-docker-compose.yml
    networks:
      - ${CONTAINER_NETWORK:-fogis-network}
    restart: unless-stopped

networks:
  fogis-network:
    external: true

volumes:
  data:
    driver: local
