groups:
  - name: match-list-change-detector
    rules:
      - alert: InstanceDown
        expr: up{job="match-list-change-detector"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

      - alert: HighErrorRate
        expr: rate(match_list_change_detector_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate on {{ $labels.instance }}"
          description: "{{ $labels.instance }} has a high error rate: {{ $value | humanizePercentage }} errors."

      - alert: MatchListFetchFailure
        expr: match_list_change_detector_fetch_failures_total > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Match list fetch failures on {{ $labels.instance }}"
          description: "{{ $labels.instance }} has failed to fetch match lists {{ $value }} times in the last 5 minutes."

      - alert: OrchestratorTriggerFailure
        expr: match_list_change_detector_orchestrator_failures_total > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Orchestrator trigger failures on {{ $labels.instance }}"
          description: "{{ $labels.instance }} has failed to trigger the orchestrator {{ $value }} times in the last 5 minutes."

      - alert: HighProcessingTime
        expr: match_list_change_detector_processing_time_seconds > 30
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High processing time on {{ $labels.instance }}"
          description: "{{ $labels.instance }} is taking more than 30 seconds to process match lists."

      - alert: NoMatchesDetected
        expr: match_list_change_detector_matches_total == 0
        for: 24h
        labels:
          severity: warning
        annotations:
          summary: "No matches detected on {{ $labels.instance }}"
          description: "{{ $labels.instance }} has not detected any matches in the last 24 hours."
