name: Contributing Guidelines Reminder

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

# Add explicit permissions
permissions:
  issues: write
  pull-requests: write
jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check issue/PR description for CONTRIBUTING.md reference
        id: check_description
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const eventName = context.eventName;
            const payload = context.payload;

            let body = '';
            let number = 0;

            if (eventName === 'issues') {
              body = payload.issue.body || '';
              number = payload.issue.number;
            } else if (eventName === 'pull_request') {
              body = payload.pull_request.body || '';
              number = payload.pull_request.number;
            }

            // Check if the body contains a reference to CONTRIBUTING.md
            const hasContributingReference = body.includes('CONTRIBUTING.md') ||
                                            body.includes('contributing guidelines') ||
                                            body.includes('contribution guidelines');

            core.setOutput('has_reference', hasContributingReference.toString());
            core.setOutput('number', number.toString());
            core.setOutput('type', eventName);

      - name: Add contributing guidelines comment if needed
        if: steps.check_description.outputs.has_reference == 'false'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const type = '${{ steps.check_description.outputs.type }}';
            const number = parseInt('${{ steps.check_description.outputs.number }}');

            let issueOrPR = 'issue';
            if (type === 'pull_request') {
              issueOrPR = 'pull request';
            }

            const comment = '## Reminder About Contributing Guidelines\n\n' +
              'When working on this ' + issueOrPR + ', please remember to follow the project\'s ' +
              '[CONTRIBUTING.md](https://github.com/timmybird/match-list-change-detector/blob/develop/CONTRIBUTING.md) ' +
              'guidelines. This is especially important for AI assistants who may not automatically check these guidelines.\n\n' +
              'Key points to remember:\n' +
              '- Follow the Gitflow workflow (feature branches from develop)\n' +
              '- Use descriptive commit messages\n' +
              '- Ensure code passes all pre-commit hooks\n' +
              '- Write tests for new functionality\n' +
              '- Update documentation as needed\n' +
              '- Follow the squash and merge strategy for PRs\n\n' +
              'Thank you for helping maintain code quality and consistency!';

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
              body: comment
            });
