name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools

    - name: Update dependencies
      run: |
        # Create a requirements.in file from requirements.txt
        grep -v "==" requirements.txt > requirements.in
        # Compile updated requirements
        pip-compile --upgrade --output-file requirements.txt requirements.in

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Update dependencies
        title: Update dependencies
        body: |
          This PR updates the project dependencies to their latest compatible versions.

          This is an automated PR created by the GitHub Actions workflow.
        branch: update-dependencies
        delete-branch: true
