name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for opening your first issue in this project! We'll review it as soon as possible."
        pr-message: "Congratulations on your first pull request to this project! We appreciate your contribution and will review it shortly."
