name: "Pull Request Labeler (Disabled)"

# This workflow is intentionally disabled
on:
  # Only run manually, not on pull requests
  workflow_dispatch:

jobs:
  # No jobs defined, so this workflow does nothing
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "This workflow is intentionally disabled"
