name: "Pull Request Labeler"

# Temporarily disable this workflow
on:
  workflow_dispatch:  # Only run manually

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    continue-on-error: true  # Don't fail the build for now
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: false  # Don't try to create missing labels
      continue-on-error: true  # Don't fail the build for now
